// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2I2A4vXrA3DRrlTz8Eew_7mHXavcd8Q',
    appId: '1:69040514457:android:2352a7cc9da16d9c4d9f08',
    messagingSenderId: '69040514457',
    projectId: 'fintech-ea16e',
    storageBucket: 'fintech-ea16e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Qeo2tNc2Q-mIZ7Kfb8Xv4QkWUh16JxE',
    appId: '1:69040514457:ios:bbb5685ee75cb80c4d9f08',
    messagingSenderId: '69040514457',
    projectId: 'fintech-ea16e',
    storageBucket: 'fintech-ea16e.firebasestorage.app',
    androidClientId: '69040514457-acikqdg7s0gorbusuvgjkci6q16fhk3s.apps.googleusercontent.com',
    iosClientId: '69040514457-5fq7vtrfkgg1q7euiv7h5ggqft52m2au.apps.googleusercontent.com',
    iosBundleId: 'com.fin.tech',
  );
}
